Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora33"

  config.vm.box_check_update = false

  config.vm.define "xdp-acl" do |m|
    m.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
      v.customize ["modifyvm", :id, "--name", "xdp-acl"]
      v.customize ["modifyvm", :id, "--nictype1", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype2", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype3", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype4", "82543GC"]
    end
    m.vm.hostname = "xdp-acl"
    m.vm.synced_folder ".", "/vagrant", disabled: false

    m.vm.network "private_network", ip: "172.20.6.3", netmask: "255.255.255.0", :mac => "040404200603"
    m.vm.network "private_network", ip: "172.20.6.5", netmask: "255.255.255.0", :mac => "040404200605"

    m.vm.provision :shell, run: "always", :inline => "ip a add 172.20.6.4/24 dev eth1 && ip a add 172.20.6.6/24 dev eth2"

    m.vm.provision :shell, run: "always", :inline => "echo \"Hi, I'm xdp-acl 🍁 \n\" && uname -a"

    # manager
    m.vm.network "private_network", ip: "172.21.6.6", netmask: "255.255.255.0", :mac => "040404210606"

    # m.vm.provision :shell, run: "always", :inline => "echo \"nameserver 223.5.5.5\" > /etc/resolv.conf", privileged: true

    m.vm.provision :shell, path: "update_xdp-acl.sh", privileged: true
  end

  config.vm.define "trafgen" do |m|
    m.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--name", "trafgen"]
      v.customize ["modifyvm", :id, "--nictype1", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype2", "82543GC"]
      v.customize ["modifyvm", :id, "--nictype3", "82543GC"]
    end
    m.vm.hostname = "trafgen"

    m.vm.synced_folder ".", "/vagrant", disabled: false

    m.vm.network "private_network", ip: "172.20.6.7", netmask: "255.255.255.0", :mac => "040404200607"

    m.vm.provision :shell, run: "always", :inline => "echo \"Hi, I'm trafgen 🍁 \n\" && uname -a"

    # manager
    m.vm.network "private_network", ip: "172.21.6.7", netmask: "255.255.255.0", :mac => "040404210606"

    # m.vm.provision :shell, run: "always", :inline => "echo \"nameserver 223.5.5.5\" > /etc/resolv.conf", privileged: true

    m.vm.provision :shell, path: "update_trafgen.sh", privileged: true
  end
end
